/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace ITorqueDriftStructs {
  export type GlobalStateStruct = {
    totalMinted: BigNumberish;
    maxSupply: BigNumberish;
    baseRate: BigNumberish;
    lastHalving: BigNumberish;
    halvingCount: BigNumberish;
    nextHalvingThreshold: BigNumberish;
    emergencyTimestamp: BigNumberish;
    pendingBaseRate: BigNumberish;
    pendingMaxSupply: BigNumberish;
    timelockExpires: BigNumberish;
    timelockDuration: BigNumberish;
    upgradeProposedAt: BigNumberish;
    totalUsers: BigNumberish;
    totalHashPower: BigNumberish;
    totalTokensClaimed: BigNumberish;
    lastStatsUpdate: BigNumberish;
    admin: AddressLike;
    tokenMint: AddressLike;
    pendingAdmin: AddressLike;
    emergencyReason: BytesLike;
    mintingPaused: boolean;
    emergencyPause: boolean;
    claimPaused: boolean;
    equipPaused: boolean;
    lockPaused: boolean;
  };

  export type GlobalStateStructOutput = [
    totalMinted: bigint,
    maxSupply: bigint,
    baseRate: bigint,
    lastHalving: bigint,
    halvingCount: bigint,
    nextHalvingThreshold: bigint,
    emergencyTimestamp: bigint,
    pendingBaseRate: bigint,
    pendingMaxSupply: bigint,
    timelockExpires: bigint,
    timelockDuration: bigint,
    upgradeProposedAt: bigint,
    totalUsers: bigint,
    totalHashPower: bigint,
    totalTokensClaimed: bigint,
    lastStatsUpdate: bigint,
    admin: string,
    tokenMint: string,
    pendingAdmin: string,
    emergencyReason: string,
    mintingPaused: boolean,
    emergencyPause: boolean,
    claimPaused: boolean,
    equipPaused: boolean,
    lockPaused: boolean
  ] & {
    totalMinted: bigint;
    maxSupply: bigint;
    baseRate: bigint;
    lastHalving: bigint;
    halvingCount: bigint;
    nextHalvingThreshold: bigint;
    emergencyTimestamp: bigint;
    pendingBaseRate: bigint;
    pendingMaxSupply: bigint;
    timelockExpires: bigint;
    timelockDuration: bigint;
    upgradeProposedAt: bigint;
    totalUsers: bigint;
    totalHashPower: bigint;
    totalTokensClaimed: bigint;
    lastStatsUpdate: bigint;
    admin: string;
    tokenMint: string;
    pendingAdmin: string;
    emergencyReason: string;
    mintingPaused: boolean;
    emergencyPause: boolean;
    claimPaused: boolean;
    equipPaused: boolean;
    lockPaused: boolean;
  };

  export type LockInfoStruct = {
    amount: BigNumberish;
    unlockTime: BigNumberish;
    boostPercent: BigNumberish;
  };

  export type LockInfoStructOutput = [
    amount: bigint,
    unlockTime: bigint,
    boostPercent: bigint
  ] & { amount: bigint; unlockTime: bigint; boostPercent: bigint };

  export type UserStateStruct = {
    lastClaim: BigNumberish;
    totalHashPower: BigNumberish;
    discount: BigNumberish;
    boostPercent: BigNumberish;
    boostStartTime: BigNumberish;
    boostDuration: BigNumberish;
    lastLockTime: BigNumberish;
    farmingPausedTime: BigNumberish;
    farmingLastPaused: BigNumberish;
    lastCarCreationDay: BigNumberish;
    dailyCarCreationCount: BigNumberish;
    totalClaimed: BigNumberish;
    referralEarnings: BigNumberish;
    referralEarningsLevel2: BigNumberish;
    cachedEffectiveHashPower: BigNumberish;
    lastEffectiveHashPowerUpdate: BigNumberish;
    lock: ITorqueDriftStructs.LockInfoStruct;
    referrer: AddressLike;
    referrerLevel2: AddressLike;
    slots: [AddressLike, AddressLike, AddressLike, AddressLike, AddressLike];
    referralCount: BigNumberish;
    equippedCar: boolean;
    gameStarted: boolean;
  };

  export type UserStateStructOutput = [
    lastClaim: bigint,
    totalHashPower: bigint,
    discount: bigint,
    boostPercent: bigint,
    boostStartTime: bigint,
    boostDuration: bigint,
    lastLockTime: bigint,
    farmingPausedTime: bigint,
    farmingLastPaused: bigint,
    lastCarCreationDay: bigint,
    dailyCarCreationCount: bigint,
    totalClaimed: bigint,
    referralEarnings: bigint,
    referralEarningsLevel2: bigint,
    cachedEffectiveHashPower: bigint,
    lastEffectiveHashPowerUpdate: bigint,
    lock: ITorqueDriftStructs.LockInfoStructOutput,
    referrer: string,
    referrerLevel2: string,
    slots: [string, string, string, string, string],
    referralCount: bigint,
    equippedCar: boolean,
    gameStarted: boolean
  ] & {
    lastClaim: bigint;
    totalHashPower: bigint;
    discount: bigint;
    boostPercent: bigint;
    boostStartTime: bigint;
    boostDuration: bigint;
    lastLockTime: bigint;
    farmingPausedTime: bigint;
    farmingLastPaused: bigint;
    lastCarCreationDay: bigint;
    dailyCarCreationCount: bigint;
    totalClaimed: bigint;
    referralEarnings: bigint;
    referralEarningsLevel2: bigint;
    cachedEffectiveHashPower: bigint;
    lastEffectiveHashPowerUpdate: bigint;
    lock: ITorqueDriftStructs.LockInfoStructOutput;
    referrer: string;
    referrerLevel2: string;
    slots: [string, string, string, string, string];
    referralCount: bigint;
    equippedCar: boolean;
    gameStarted: boolean;
  };
}

export interface TorqueDriftReferralInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_TIMELOCK_DURATION"
      | "MIN_CLAIM_COOLDOWN"
      | "PENALTY_1H_BURN_BPS"
      | "PENALTY_1H_SOL"
      | "PENALTY_2H_BURN_BPS"
      | "PENALTY_2H_SOL"
      | "PENALTY_3H_BURN_BPS"
      | "PENALTY_3H_SOL"
      | "PENALTY_4H_BURN_BPS"
      | "PENALTY_4H_SOL"
      | "REFERRAL_BOOST_DURATION"
      | "SECONDS_PER_DAY"
      | "SECONDS_PER_HOUR"
      | "activateClaimLock"
      | "advancedContract"
      | "calculateMaintenanceCost"
      | "carsContract"
      | "claimTokens"
      | "createReferralCode"
      | "deactivateClaimLock"
      | "discountReferralCodes"
      | "emergencyRescueTokens"
      | "equipCar"
      | "equippedCars"
      | "gameContract"
      | "getContractVersion"
      | "getDiscountReferralCodesStatus"
      | "getGlobalState"
      | "getReferralDiscountInfo"
      | "getReferralInfo"
      | "getUserDailyCarCreationInfo"
      | "getUserGameStarted"
      | "getUserInfo"
      | "getUserReferralCode"
      | "getUserReferralCount"
      | "getUserReferrer"
      | "getUserState"
      | "getUserTotalClaimed"
      | "getUserTotalEarned"
      | "globalState"
      | "hasActiveClaimLock"
      | "initializeStartGame"
      | "initializeStartGameWithReferral"
      | "isValidReferralCode"
      | "owner"
      | "payMaintenance"
      | "performMaintenance(uint8)"
      | "performMaintenance(address)"
      | "previewClaim"
      | "referralCodeToAddress"
      | "referralCounts"
      | "referralDiscountBalance"
      | "referrals"
      | "setAdvancedContract"
      | "setCarsContract"
      | "setDiscountReferralCodes"
      | "setGameContract"
      | "setTokenContract"
      | "specialReferralCount"
      | "syncUserHashPower"
      | "tokenContract"
      | "totalTokensClaimed"
      | "totalUsers"
      | "treasuryWallet"
      | "unequipCar"
      | "userStates"
      | "withdrawReferralDiscounts"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdvancedContractUpdated"
      | "BnbPenaltyUpdated"
      | "BurnPenaltyUpdated"
      | "CarCreated"
      | "CarEquipped"
      | "CarMaintained"
      | "CarMaintenance"
      | "CarUnequipped"
      | "ClockDriftToleranceUpdated"
      | "DebugInitialize"
      | "DiscountReferralApplied"
      | "DiscountReferralCodeUpdated"
      | "GameStarted"
      | "HalvingTriggered"
      | "MinClaimCooldownUpdated"
      | "ReferralApplied"
      | "ReferralBoostDurationUpdated"
      | "ReferralCodeCreated"
      | "ReferralDiscountWithdrawn"
      | "TokensClaimed"
      | "TreasuryWalletUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_TIMELOCK_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_CLAIM_COOLDOWN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PENALTY_1H_BURN_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PENALTY_1H_SOL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PENALTY_2H_BURN_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PENALTY_2H_SOL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PENALTY_3H_BURN_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PENALTY_3H_SOL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PENALTY_4H_BURN_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PENALTY_4H_SOL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REFERRAL_BOOST_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SECONDS_PER_DAY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SECONDS_PER_HOUR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activateClaimLock",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "advancedContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "calculateMaintenanceCost",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "carsContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createReferralCode",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateClaimLock",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "discountReferralCodes",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyRescueTokens",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "equipCar",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "equippedCars",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "gameContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getContractVersion",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDiscountReferralCodesStatus",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getGlobalState",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getReferralDiscountInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getReferralInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserDailyCarCreationInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserGameStarted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserReferralCode",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserReferralCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserReferrer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserState",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserTotalClaimed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserTotalEarned",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "globalState",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasActiveClaimLock",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initializeStartGame",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initializeStartGameWithReferral",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidReferralCode",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payMaintenance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "performMaintenance(uint8)",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "performMaintenance(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "previewClaim",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "referralCodeToAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "referralCounts",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "referralDiscountBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "referrals",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAdvancedContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setCarsContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setDiscountReferralCodes",
    values: [string[], boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setGameContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "specialReferralCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "syncUserHashPower",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalTokensClaimed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalUsers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "treasuryWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "unequipCar",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userStates",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawReferralDiscounts",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_TIMELOCK_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_CLAIM_COOLDOWN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PENALTY_1H_BURN_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PENALTY_1H_SOL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PENALTY_2H_BURN_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PENALTY_2H_SOL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PENALTY_3H_BURN_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PENALTY_3H_SOL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PENALTY_4H_BURN_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PENALTY_4H_SOL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REFERRAL_BOOST_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SECONDS_PER_DAY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SECONDS_PER_HOUR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activateClaimLock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "advancedContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateMaintenanceCost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "carsContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createReferralCode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateClaimLock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "discountReferralCodes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyRescueTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "equipCar", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "equippedCars",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gameContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractVersion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDiscountReferralCodesStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGlobalState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReferralDiscountInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReferralInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserDailyCarCreationInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserGameStarted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserReferralCode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserReferralCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserReferrer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserTotalClaimed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserTotalEarned",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "globalState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasActiveClaimLock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializeStartGame",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializeStartGameWithReferral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidReferralCode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "payMaintenance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "performMaintenance(uint8)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "performMaintenance(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "previewClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "referralCodeToAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "referralCounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "referralDiscountBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "referrals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAdvancedContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCarsContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDiscountReferralCodes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGameContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "specialReferralCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "syncUserHashPower",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalTokensClaimed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalUsers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "treasuryWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unequipCar", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "userStates", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawReferralDiscounts",
    data: BytesLike
  ): Result;
}

export namespace AdvancedContractUpdatedEvent {
  export type InputTuple = [advancedContract: AddressLike];
  export type OutputTuple = [advancedContract: string];
  export interface OutputObject {
    advancedContract: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BnbPenaltyUpdatedEvent {
  export type InputTuple = [
    penaltyType: string,
    oldAmount: BigNumberish,
    newAmount: BigNumberish
  ];
  export type OutputTuple = [
    penaltyType: string,
    oldAmount: bigint,
    newAmount: bigint
  ];
  export interface OutputObject {
    penaltyType: string;
    oldAmount: bigint;
    newAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BurnPenaltyUpdatedEvent {
  export type InputTuple = [
    penaltyType: string,
    oldBps: BigNumberish,
    newBps: BigNumberish
  ];
  export type OutputTuple = [
    penaltyType: string,
    oldBps: bigint,
    newBps: bigint
  ];
  export interface OutputObject {
    penaltyType: string;
    oldBps: bigint;
    newBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CarCreatedEvent {
  export type InputTuple = [
    user: AddressLike,
    carId: BigNumberish,
    rarity: BigNumberish,
    version: BigNumberish,
    hashPower: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    carId: bigint,
    rarity: bigint,
    version: bigint,
    hashPower: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    carId: bigint;
    rarity: bigint;
    version: bigint;
    hashPower: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CarEquippedEvent {
  export type InputTuple = [
    user: AddressLike,
    carAddress: AddressLike,
    hashPower: BigNumberish,
    slotIndex: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    carAddress: string,
    hashPower: bigint,
    slotIndex: bigint
  ];
  export interface OutputObject {
    user: string;
    carAddress: string;
    hashPower: bigint;
    slotIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CarMaintainedEvent {
  export type InputTuple = [
    user: AddressLike,
    carAddress: AddressLike,
    slotIndex: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    carAddress: string,
    slotIndex: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    carAddress: string;
    slotIndex: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CarMaintenanceEvent {
  export type InputTuple = [
    user: AddressLike,
    carAddress: AddressLike,
    maintenanceCost: BigNumberish,
    oldEfficiency: BigNumberish,
    newEfficiency: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    carAddress: string,
    maintenanceCost: bigint,
    oldEfficiency: bigint,
    newEfficiency: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    carAddress: string;
    maintenanceCost: bigint;
    oldEfficiency: bigint;
    newEfficiency: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CarUnequippedEvent {
  export type InputTuple = [
    user: AddressLike,
    carAddress: AddressLike,
    slotIndex: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    carAddress: string,
    slotIndex: bigint
  ];
  export interface OutputObject {
    user: string;
    carAddress: string;
    slotIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClockDriftToleranceUpdatedEvent {
  export type InputTuple = [oldValue: BigNumberish, newValue: BigNumberish];
  export type OutputTuple = [oldValue: bigint, newValue: bigint];
  export interface OutputObject {
    oldValue: bigint;
    newValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DebugInitializeEvent {
  export type InputTuple = [
    msgSender: AddressLike,
    txOrigin: AddressLike,
    gameContract: AddressLike,
    thisContract: AddressLike
  ];
  export type OutputTuple = [
    msgSender: string,
    txOrigin: string,
    gameContract: string,
    thisContract: string
  ];
  export interface OutputObject {
    msgSender: string;
    txOrigin: string;
    gameContract: string;
    thisContract: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DiscountReferralAppliedEvent {
  export type InputTuple = [
    referrer: AddressLike,
    referee: AddressLike,
    discountAmount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    referrer: string,
    referee: string,
    discountAmount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    referrer: string;
    referee: string;
    discountAmount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DiscountReferralCodeUpdatedEvent {
  export type InputTuple = [
    code: string,
    referrer: AddressLike,
    enabled: boolean,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    code: string,
    referrer: string,
    enabled: boolean,
    timestamp: bigint
  ];
  export interface OutputObject {
    code: string;
    referrer: string;
    enabled: boolean;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameStartedEvent {
  export type InputTuple = [
    user: AddressLike,
    bnbPaid: BigNumberish,
    starterCar: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    bnbPaid: bigint,
    starterCar: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    bnbPaid: bigint;
    starterCar: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HalvingTriggeredEvent {
  export type InputTuple = [
    halvingCount: BigNumberish,
    newBaseRate: BigNumberish,
    nextHalvingThreshold: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    halvingCount: bigint,
    newBaseRate: bigint,
    nextHalvingThreshold: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    halvingCount: bigint;
    newBaseRate: bigint;
    nextHalvingThreshold: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinClaimCooldownUpdatedEvent {
  export type InputTuple = [oldValue: BigNumberish, newValue: BigNumberish];
  export type OutputTuple = [oldValue: bigint, newValue: bigint];
  export interface OutputObject {
    oldValue: bigint;
    newValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReferralAppliedEvent {
  export type InputTuple = [
    referrer: AddressLike,
    referee: AddressLike,
    referrerBoost: BigNumberish,
    refereeDiscount: BigNumberish,
    boostDuration: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    referrer: string,
    referee: string,
    referrerBoost: bigint,
    refereeDiscount: bigint,
    boostDuration: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    referrer: string;
    referee: string;
    referrerBoost: bigint;
    refereeDiscount: bigint;
    boostDuration: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReferralBoostDurationUpdatedEvent {
  export type InputTuple = [oldValue: BigNumberish, newValue: BigNumberish];
  export type OutputTuple = [oldValue: bigint, newValue: bigint];
  export interface OutputObject {
    oldValue: bigint;
    newValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReferralCodeCreatedEvent {
  export type InputTuple = [
    user: AddressLike,
    code: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [user: string, code: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    code: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReferralDiscountWithdrawnEvent {
  export type InputTuple = [
    referrer: AddressLike,
    amount: BigNumberish,
    specialReferralCount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    referrer: string,
    amount: bigint,
    specialReferralCount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    referrer: string;
    amount: bigint;
    specialReferralCount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensClaimedEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [user: string, amount: bigint, timestamp: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryWalletUpdatedEvent {
  export type InputTuple = [oldWallet: AddressLike, newWallet: AddressLike];
  export type OutputTuple = [oldWallet: string, newWallet: string];
  export interface OutputObject {
    oldWallet: string;
    newWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TorqueDriftReferral extends BaseContract {
  connect(runner?: ContractRunner | null): TorqueDriftReferral;
  waitForDeployment(): Promise<this>;

  interface: TorqueDriftReferralInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_TIMELOCK_DURATION: TypedContractMethod<[], [bigint], "view">;

  MIN_CLAIM_COOLDOWN: TypedContractMethod<[], [bigint], "view">;

  PENALTY_1H_BURN_BPS: TypedContractMethod<[], [bigint], "view">;

  PENALTY_1H_SOL: TypedContractMethod<[], [bigint], "view">;

  PENALTY_2H_BURN_BPS: TypedContractMethod<[], [bigint], "view">;

  PENALTY_2H_SOL: TypedContractMethod<[], [bigint], "view">;

  PENALTY_3H_BURN_BPS: TypedContractMethod<[], [bigint], "view">;

  PENALTY_3H_SOL: TypedContractMethod<[], [bigint], "view">;

  PENALTY_4H_BURN_BPS: TypedContractMethod<[], [bigint], "view">;

  PENALTY_4H_SOL: TypedContractMethod<[], [bigint], "view">;

  REFERRAL_BOOST_DURATION: TypedContractMethod<[], [bigint], "view">;

  SECONDS_PER_DAY: TypedContractMethod<[], [bigint], "view">;

  SECONDS_PER_HOUR: TypedContractMethod<[], [bigint], "view">;

  activateClaimLock: TypedContractMethod<
    [lockOption: BigNumberish],
    [void],
    "nonpayable"
  >;

  advancedContract: TypedContractMethod<[], [string], "view">;

  calculateMaintenanceCost: TypedContractMethod<
    [carAddress: AddressLike],
    [[bigint, boolean] & { cost: bigint; canMaintain: boolean }],
    "view"
  >;

  carsContract: TypedContractMethod<[], [string], "view">;

  claimTokens: TypedContractMethod<[], [void], "payable">;

  createReferralCode: TypedContractMethod<[code: string], [void], "nonpayable">;

  deactivateClaimLock: TypedContractMethod<[], [void], "nonpayable">;

  discountReferralCodes: TypedContractMethod<[arg0: string], [boolean], "view">;

  emergencyRescueTokens: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  equipCar: TypedContractMethod<
    [carAddress: AddressLike, slotIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  equippedCars: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, bigint, bigint] & {
        mint: string;
        hashPower: bigint;
        efficiency: bigint;
        lastMaintenance: bigint;
        rarity: bigint;
        version: bigint;
        slotIndex: bigint;
      }
    ],
    "view"
  >;

  gameContract: TypedContractMethod<[], [string], "view">;

  getContractVersion: TypedContractMethod<[], [string], "view">;

  getDiscountReferralCodesStatus: TypedContractMethod<
    [codes: string[]],
    [boolean[]],
    "view"
  >;

  getGlobalState: TypedContractMethod<
    [],
    [ITorqueDriftStructs.GlobalStateStructOutput],
    "view"
  >;

  getReferralDiscountInfo: TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, boolean, bigint] & {
        balance: bigint;
        specialCount: bigint;
        canWithdraw: boolean;
        totalDiscountEarned: bigint;
      }
    ],
    "view"
  >;

  getReferralInfo: TypedContractMethod<
    [user: AddressLike],
    [
      [string, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        referrer_: string;
        referralEarnings_: bigint;
        referralEarningsLevel2_: bigint;
        referralCount_: bigint;
        discount_: bigint;
        boostPercent_: bigint;
        boostStartTime_: bigint;
        boostDuration_: bigint;
      }
    ],
    "view"
  >;

  getUserDailyCarCreationInfo: TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint] & {
        dailyCarCreationCount: bigint;
        maxDailyCarCreations: bigint;
        nextResetTime: bigint;
      }
    ],
    "view"
  >;

  getUserGameStarted: TypedContractMethod<
    [user: AddressLike],
    [boolean],
    "view"
  >;

  getUserInfo: TypedContractMethod<
    [],
    [
      [boolean, bigint, bigint, bigint, boolean, bigint, bigint] & {
        gameStarted_: boolean;
        totalHashPower: bigint;
        lastClaim: bigint;
        discount: bigint;
        equippedCar: boolean;
        boostPercent: bigint;
        equippedCount: bigint;
      }
    ],
    "view"
  >;

  getUserReferralCode: TypedContractMethod<
    [user: AddressLike],
    [string],
    "view"
  >;

  getUserReferralCount: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getUserReferrer: TypedContractMethod<[user: AddressLike], [string], "view">;

  getUserState: TypedContractMethod<
    [user: AddressLike],
    [ITorqueDriftStructs.UserStateStructOutput],
    "view"
  >;

  getUserTotalClaimed: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getUserTotalEarned: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  globalState: TypedContractMethod<
    [],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        string,
        string,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean
      ] & {
        totalMinted: bigint;
        maxSupply: bigint;
        baseRate: bigint;
        lastHalving: bigint;
        halvingCount: bigint;
        nextHalvingThreshold: bigint;
        emergencyTimestamp: bigint;
        pendingBaseRate: bigint;
        pendingMaxSupply: bigint;
        timelockExpires: bigint;
        timelockDuration: bigint;
        upgradeProposedAt: bigint;
        totalUsers: bigint;
        totalHashPower: bigint;
        totalTokensClaimed: bigint;
        lastStatsUpdate: bigint;
        admin: string;
        tokenMint: string;
        pendingAdmin: string;
        emergencyReason: string;
        mintingPaused: boolean;
        emergencyPause: boolean;
        claimPaused: boolean;
        equipPaused: boolean;
        lockPaused: boolean;
      }
    ],
    "view"
  >;

  hasActiveClaimLock: TypedContractMethod<
    [user: AddressLike],
    [boolean],
    "view"
  >;

  initializeStartGame: TypedContractMethod<
    [referrer: AddressLike],
    [void],
    "payable"
  >;

  initializeStartGameWithReferral: TypedContractMethod<
    [referrerCode: string],
    [void],
    "payable"
  >;

  isValidReferralCode: TypedContractMethod<[code: string], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  payMaintenance: TypedContractMethod<
    [carAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  "performMaintenance(uint8)": TypedContractMethod<
    [slotIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  "performMaintenance(address)": TypedContractMethod<
    [carAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  previewClaim: TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        claimableAmount: bigint;
        baseReward: bigint;
        lockBoost: bigint;
        referralBoost: bigint;
        hourlyReward: bigint;
      }
    ],
    "view"
  >;

  referralCodeToAddress: TypedContractMethod<[arg0: string], [string], "view">;

  referralCounts: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  referralDiscountBalance: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  referrals: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  setAdvancedContract: TypedContractMethod<
    [_advancedContract: AddressLike],
    [void],
    "nonpayable"
  >;

  setCarsContract: TypedContractMethod<
    [_carsContract: AddressLike],
    [void],
    "nonpayable"
  >;

  setDiscountReferralCodes: TypedContractMethod<
    [codes: string[], enabled: boolean],
    [void],
    "nonpayable"
  >;

  setGameContract: TypedContractMethod<
    [_gameContract: AddressLike],
    [void],
    "nonpayable"
  >;

  setTokenContract: TypedContractMethod<
    [_tokenContract: AddressLike],
    [void],
    "nonpayable"
  >;

  specialReferralCount: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  syncUserHashPower: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "nonpayable"
  >;

  tokenContract: TypedContractMethod<[], [string], "view">;

  totalTokensClaimed: TypedContractMethod<[], [bigint], "view">;

  totalUsers: TypedContractMethod<[], [bigint], "view">;

  treasuryWallet: TypedContractMethod<[], [string], "view">;

  unequipCar: TypedContractMethod<
    [carAddress: AddressLike, slotIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  userStates: TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        ITorqueDriftStructs.LockInfoStructOutput,
        string,
        string,
        bigint,
        boolean,
        boolean
      ] & {
        lastClaim: bigint;
        totalHashPower: bigint;
        discount: bigint;
        boostPercent: bigint;
        boostStartTime: bigint;
        boostDuration: bigint;
        lastLockTime: bigint;
        farmingPausedTime: bigint;
        farmingLastPaused: bigint;
        lastCarCreationDay: bigint;
        dailyCarCreationCount: bigint;
        totalClaimed: bigint;
        referralEarnings: bigint;
        referralEarningsLevel2: bigint;
        cachedEffectiveHashPower: bigint;
        lastEffectiveHashPowerUpdate: bigint;
        lock: ITorqueDriftStructs.LockInfoStructOutput;
        referrer: string;
        referrerLevel2: string;
        referralCount: bigint;
        equippedCar: boolean;
        gameStarted: boolean;
      }
    ],
    "view"
  >;

  withdrawReferralDiscounts: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_TIMELOCK_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_CLAIM_COOLDOWN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PENALTY_1H_BURN_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PENALTY_1H_SOL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PENALTY_2H_BURN_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PENALTY_2H_SOL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PENALTY_3H_BURN_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PENALTY_3H_SOL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PENALTY_4H_BURN_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PENALTY_4H_SOL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REFERRAL_BOOST_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SECONDS_PER_DAY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SECONDS_PER_HOUR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "activateClaimLock"
  ): TypedContractMethod<[lockOption: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "advancedContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "calculateMaintenanceCost"
  ): TypedContractMethod<
    [carAddress: AddressLike],
    [[bigint, boolean] & { cost: bigint; canMaintain: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "carsContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "claimTokens"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "createReferralCode"
  ): TypedContractMethod<[code: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deactivateClaimLock"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "discountReferralCodes"
  ): TypedContractMethod<[arg0: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "emergencyRescueTokens"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "equipCar"
  ): TypedContractMethod<
    [carAddress: AddressLike, slotIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "equippedCars"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, bigint, bigint] & {
        mint: string;
        hashPower: bigint;
        efficiency: bigint;
        lastMaintenance: bigint;
        rarity: bigint;
        version: bigint;
        slotIndex: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "gameContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getContractVersion"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getDiscountReferralCodesStatus"
  ): TypedContractMethod<[codes: string[]], [boolean[]], "view">;
  getFunction(
    nameOrSignature: "getGlobalState"
  ): TypedContractMethod<
    [],
    [ITorqueDriftStructs.GlobalStateStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReferralDiscountInfo"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, boolean, bigint] & {
        balance: bigint;
        specialCount: bigint;
        canWithdraw: boolean;
        totalDiscountEarned: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReferralInfo"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [string, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        referrer_: string;
        referralEarnings_: bigint;
        referralEarningsLevel2_: bigint;
        referralCount_: bigint;
        discount_: bigint;
        boostPercent_: bigint;
        boostStartTime_: bigint;
        boostDuration_: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserDailyCarCreationInfo"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint] & {
        dailyCarCreationCount: bigint;
        maxDailyCarCreations: bigint;
        nextResetTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserGameStarted"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getUserInfo"
  ): TypedContractMethod<
    [],
    [
      [boolean, bigint, bigint, bigint, boolean, bigint, bigint] & {
        gameStarted_: boolean;
        totalHashPower: bigint;
        lastClaim: bigint;
        discount: bigint;
        equippedCar: boolean;
        boostPercent: bigint;
        equippedCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserReferralCode"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getUserReferralCount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserReferrer"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getUserState"
  ): TypedContractMethod<
    [user: AddressLike],
    [ITorqueDriftStructs.UserStateStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserTotalClaimed"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserTotalEarned"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "globalState"
  ): TypedContractMethod<
    [],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        string,
        string,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean
      ] & {
        totalMinted: bigint;
        maxSupply: bigint;
        baseRate: bigint;
        lastHalving: bigint;
        halvingCount: bigint;
        nextHalvingThreshold: bigint;
        emergencyTimestamp: bigint;
        pendingBaseRate: bigint;
        pendingMaxSupply: bigint;
        timelockExpires: bigint;
        timelockDuration: bigint;
        upgradeProposedAt: bigint;
        totalUsers: bigint;
        totalHashPower: bigint;
        totalTokensClaimed: bigint;
        lastStatsUpdate: bigint;
        admin: string;
        tokenMint: string;
        pendingAdmin: string;
        emergencyReason: string;
        mintingPaused: boolean;
        emergencyPause: boolean;
        claimPaused: boolean;
        equipPaused: boolean;
        lockPaused: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasActiveClaimLock"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "initializeStartGame"
  ): TypedContractMethod<[referrer: AddressLike], [void], "payable">;
  getFunction(
    nameOrSignature: "initializeStartGameWithReferral"
  ): TypedContractMethod<[referrerCode: string], [void], "payable">;
  getFunction(
    nameOrSignature: "isValidReferralCode"
  ): TypedContractMethod<[code: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "payMaintenance"
  ): TypedContractMethod<[carAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "performMaintenance(uint8)"
  ): TypedContractMethod<[slotIndex: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "performMaintenance(address)"
  ): TypedContractMethod<[carAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "previewClaim"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        claimableAmount: bigint;
        baseReward: bigint;
        lockBoost: bigint;
        referralBoost: bigint;
        hourlyReward: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "referralCodeToAddress"
  ): TypedContractMethod<[arg0: string], [string], "view">;
  getFunction(
    nameOrSignature: "referralCounts"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "referralDiscountBalance"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "referrals"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "setAdvancedContract"
  ): TypedContractMethod<
    [_advancedContract: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setCarsContract"
  ): TypedContractMethod<[_carsContract: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDiscountReferralCodes"
  ): TypedContractMethod<
    [codes: string[], enabled: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setGameContract"
  ): TypedContractMethod<[_gameContract: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTokenContract"
  ): TypedContractMethod<[_tokenContract: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "specialReferralCount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "syncUserHashPower"
  ): TypedContractMethod<[user: AddressLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "tokenContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalTokensClaimed"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalUsers"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "treasuryWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unequipCar"
  ): TypedContractMethod<
    [carAddress: AddressLike, slotIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userStates"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        ITorqueDriftStructs.LockInfoStructOutput,
        string,
        string,
        bigint,
        boolean,
        boolean
      ] & {
        lastClaim: bigint;
        totalHashPower: bigint;
        discount: bigint;
        boostPercent: bigint;
        boostStartTime: bigint;
        boostDuration: bigint;
        lastLockTime: bigint;
        farmingPausedTime: bigint;
        farmingLastPaused: bigint;
        lastCarCreationDay: bigint;
        dailyCarCreationCount: bigint;
        totalClaimed: bigint;
        referralEarnings: bigint;
        referralEarningsLevel2: bigint;
        cachedEffectiveHashPower: bigint;
        lastEffectiveHashPowerUpdate: bigint;
        lock: ITorqueDriftStructs.LockInfoStructOutput;
        referrer: string;
        referrerLevel2: string;
        referralCount: bigint;
        equippedCar: boolean;
        gameStarted: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawReferralDiscounts"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "AdvancedContractUpdated"
  ): TypedContractEvent<
    AdvancedContractUpdatedEvent.InputTuple,
    AdvancedContractUpdatedEvent.OutputTuple,
    AdvancedContractUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "BnbPenaltyUpdated"
  ): TypedContractEvent<
    BnbPenaltyUpdatedEvent.InputTuple,
    BnbPenaltyUpdatedEvent.OutputTuple,
    BnbPenaltyUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "BurnPenaltyUpdated"
  ): TypedContractEvent<
    BurnPenaltyUpdatedEvent.InputTuple,
    BurnPenaltyUpdatedEvent.OutputTuple,
    BurnPenaltyUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "CarCreated"
  ): TypedContractEvent<
    CarCreatedEvent.InputTuple,
    CarCreatedEvent.OutputTuple,
    CarCreatedEvent.OutputObject
  >;
  getEvent(
    key: "CarEquipped"
  ): TypedContractEvent<
    CarEquippedEvent.InputTuple,
    CarEquippedEvent.OutputTuple,
    CarEquippedEvent.OutputObject
  >;
  getEvent(
    key: "CarMaintained"
  ): TypedContractEvent<
    CarMaintainedEvent.InputTuple,
    CarMaintainedEvent.OutputTuple,
    CarMaintainedEvent.OutputObject
  >;
  getEvent(
    key: "CarMaintenance"
  ): TypedContractEvent<
    CarMaintenanceEvent.InputTuple,
    CarMaintenanceEvent.OutputTuple,
    CarMaintenanceEvent.OutputObject
  >;
  getEvent(
    key: "CarUnequipped"
  ): TypedContractEvent<
    CarUnequippedEvent.InputTuple,
    CarUnequippedEvent.OutputTuple,
    CarUnequippedEvent.OutputObject
  >;
  getEvent(
    key: "ClockDriftToleranceUpdated"
  ): TypedContractEvent<
    ClockDriftToleranceUpdatedEvent.InputTuple,
    ClockDriftToleranceUpdatedEvent.OutputTuple,
    ClockDriftToleranceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DebugInitialize"
  ): TypedContractEvent<
    DebugInitializeEvent.InputTuple,
    DebugInitializeEvent.OutputTuple,
    DebugInitializeEvent.OutputObject
  >;
  getEvent(
    key: "DiscountReferralApplied"
  ): TypedContractEvent<
    DiscountReferralAppliedEvent.InputTuple,
    DiscountReferralAppliedEvent.OutputTuple,
    DiscountReferralAppliedEvent.OutputObject
  >;
  getEvent(
    key: "DiscountReferralCodeUpdated"
  ): TypedContractEvent<
    DiscountReferralCodeUpdatedEvent.InputTuple,
    DiscountReferralCodeUpdatedEvent.OutputTuple,
    DiscountReferralCodeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "GameStarted"
  ): TypedContractEvent<
    GameStartedEvent.InputTuple,
    GameStartedEvent.OutputTuple,
    GameStartedEvent.OutputObject
  >;
  getEvent(
    key: "HalvingTriggered"
  ): TypedContractEvent<
    HalvingTriggeredEvent.InputTuple,
    HalvingTriggeredEvent.OutputTuple,
    HalvingTriggeredEvent.OutputObject
  >;
  getEvent(
    key: "MinClaimCooldownUpdated"
  ): TypedContractEvent<
    MinClaimCooldownUpdatedEvent.InputTuple,
    MinClaimCooldownUpdatedEvent.OutputTuple,
    MinClaimCooldownUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ReferralApplied"
  ): TypedContractEvent<
    ReferralAppliedEvent.InputTuple,
    ReferralAppliedEvent.OutputTuple,
    ReferralAppliedEvent.OutputObject
  >;
  getEvent(
    key: "ReferralBoostDurationUpdated"
  ): TypedContractEvent<
    ReferralBoostDurationUpdatedEvent.InputTuple,
    ReferralBoostDurationUpdatedEvent.OutputTuple,
    ReferralBoostDurationUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ReferralCodeCreated"
  ): TypedContractEvent<
    ReferralCodeCreatedEvent.InputTuple,
    ReferralCodeCreatedEvent.OutputTuple,
    ReferralCodeCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ReferralDiscountWithdrawn"
  ): TypedContractEvent<
    ReferralDiscountWithdrawnEvent.InputTuple,
    ReferralDiscountWithdrawnEvent.OutputTuple,
    ReferralDiscountWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "TokensClaimed"
  ): TypedContractEvent<
    TokensClaimedEvent.InputTuple,
    TokensClaimedEvent.OutputTuple,
    TokensClaimedEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryWalletUpdated"
  ): TypedContractEvent<
    TreasuryWalletUpdatedEvent.InputTuple,
    TreasuryWalletUpdatedEvent.OutputTuple,
    TreasuryWalletUpdatedEvent.OutputObject
  >;

  filters: {
    "AdvancedContractUpdated(address)": TypedContractEvent<
      AdvancedContractUpdatedEvent.InputTuple,
      AdvancedContractUpdatedEvent.OutputTuple,
      AdvancedContractUpdatedEvent.OutputObject
    >;
    AdvancedContractUpdated: TypedContractEvent<
      AdvancedContractUpdatedEvent.InputTuple,
      AdvancedContractUpdatedEvent.OutputTuple,
      AdvancedContractUpdatedEvent.OutputObject
    >;

    "BnbPenaltyUpdated(string,uint256,uint256)": TypedContractEvent<
      BnbPenaltyUpdatedEvent.InputTuple,
      BnbPenaltyUpdatedEvent.OutputTuple,
      BnbPenaltyUpdatedEvent.OutputObject
    >;
    BnbPenaltyUpdated: TypedContractEvent<
      BnbPenaltyUpdatedEvent.InputTuple,
      BnbPenaltyUpdatedEvent.OutputTuple,
      BnbPenaltyUpdatedEvent.OutputObject
    >;

    "BurnPenaltyUpdated(string,uint256,uint256)": TypedContractEvent<
      BurnPenaltyUpdatedEvent.InputTuple,
      BurnPenaltyUpdatedEvent.OutputTuple,
      BurnPenaltyUpdatedEvent.OutputObject
    >;
    BurnPenaltyUpdated: TypedContractEvent<
      BurnPenaltyUpdatedEvent.InputTuple,
      BurnPenaltyUpdatedEvent.OutputTuple,
      BurnPenaltyUpdatedEvent.OutputObject
    >;

    "CarCreated(address,uint256,uint8,uint8,uint256,uint256)": TypedContractEvent<
      CarCreatedEvent.InputTuple,
      CarCreatedEvent.OutputTuple,
      CarCreatedEvent.OutputObject
    >;
    CarCreated: TypedContractEvent<
      CarCreatedEvent.InputTuple,
      CarCreatedEvent.OutputTuple,
      CarCreatedEvent.OutputObject
    >;

    "CarEquipped(address,address,uint256,uint8)": TypedContractEvent<
      CarEquippedEvent.InputTuple,
      CarEquippedEvent.OutputTuple,
      CarEquippedEvent.OutputObject
    >;
    CarEquipped: TypedContractEvent<
      CarEquippedEvent.InputTuple,
      CarEquippedEvent.OutputTuple,
      CarEquippedEvent.OutputObject
    >;

    "CarMaintained(address,address,uint8,uint256)": TypedContractEvent<
      CarMaintainedEvent.InputTuple,
      CarMaintainedEvent.OutputTuple,
      CarMaintainedEvent.OutputObject
    >;
    CarMaintained: TypedContractEvent<
      CarMaintainedEvent.InputTuple,
      CarMaintainedEvent.OutputTuple,
      CarMaintainedEvent.OutputObject
    >;

    "CarMaintenance(address,address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      CarMaintenanceEvent.InputTuple,
      CarMaintenanceEvent.OutputTuple,
      CarMaintenanceEvent.OutputObject
    >;
    CarMaintenance: TypedContractEvent<
      CarMaintenanceEvent.InputTuple,
      CarMaintenanceEvent.OutputTuple,
      CarMaintenanceEvent.OutputObject
    >;

    "CarUnequipped(address,address,uint8)": TypedContractEvent<
      CarUnequippedEvent.InputTuple,
      CarUnequippedEvent.OutputTuple,
      CarUnequippedEvent.OutputObject
    >;
    CarUnequipped: TypedContractEvent<
      CarUnequippedEvent.InputTuple,
      CarUnequippedEvent.OutputTuple,
      CarUnequippedEvent.OutputObject
    >;

    "ClockDriftToleranceUpdated(uint256,uint256)": TypedContractEvent<
      ClockDriftToleranceUpdatedEvent.InputTuple,
      ClockDriftToleranceUpdatedEvent.OutputTuple,
      ClockDriftToleranceUpdatedEvent.OutputObject
    >;
    ClockDriftToleranceUpdated: TypedContractEvent<
      ClockDriftToleranceUpdatedEvent.InputTuple,
      ClockDriftToleranceUpdatedEvent.OutputTuple,
      ClockDriftToleranceUpdatedEvent.OutputObject
    >;

    "DebugInitialize(address,address,address,address)": TypedContractEvent<
      DebugInitializeEvent.InputTuple,
      DebugInitializeEvent.OutputTuple,
      DebugInitializeEvent.OutputObject
    >;
    DebugInitialize: TypedContractEvent<
      DebugInitializeEvent.InputTuple,
      DebugInitializeEvent.OutputTuple,
      DebugInitializeEvent.OutputObject
    >;

    "DiscountReferralApplied(address,address,uint256,uint256)": TypedContractEvent<
      DiscountReferralAppliedEvent.InputTuple,
      DiscountReferralAppliedEvent.OutputTuple,
      DiscountReferralAppliedEvent.OutputObject
    >;
    DiscountReferralApplied: TypedContractEvent<
      DiscountReferralAppliedEvent.InputTuple,
      DiscountReferralAppliedEvent.OutputTuple,
      DiscountReferralAppliedEvent.OutputObject
    >;

    "DiscountReferralCodeUpdated(string,address,bool,uint256)": TypedContractEvent<
      DiscountReferralCodeUpdatedEvent.InputTuple,
      DiscountReferralCodeUpdatedEvent.OutputTuple,
      DiscountReferralCodeUpdatedEvent.OutputObject
    >;
    DiscountReferralCodeUpdated: TypedContractEvent<
      DiscountReferralCodeUpdatedEvent.InputTuple,
      DiscountReferralCodeUpdatedEvent.OutputTuple,
      DiscountReferralCodeUpdatedEvent.OutputObject
    >;

    "GameStarted(address,uint256,address,uint256)": TypedContractEvent<
      GameStartedEvent.InputTuple,
      GameStartedEvent.OutputTuple,
      GameStartedEvent.OutputObject
    >;
    GameStarted: TypedContractEvent<
      GameStartedEvent.InputTuple,
      GameStartedEvent.OutputTuple,
      GameStartedEvent.OutputObject
    >;

    "HalvingTriggered(uint256,uint256,uint256,uint256)": TypedContractEvent<
      HalvingTriggeredEvent.InputTuple,
      HalvingTriggeredEvent.OutputTuple,
      HalvingTriggeredEvent.OutputObject
    >;
    HalvingTriggered: TypedContractEvent<
      HalvingTriggeredEvent.InputTuple,
      HalvingTriggeredEvent.OutputTuple,
      HalvingTriggeredEvent.OutputObject
    >;

    "MinClaimCooldownUpdated(uint256,uint256)": TypedContractEvent<
      MinClaimCooldownUpdatedEvent.InputTuple,
      MinClaimCooldownUpdatedEvent.OutputTuple,
      MinClaimCooldownUpdatedEvent.OutputObject
    >;
    MinClaimCooldownUpdated: TypedContractEvent<
      MinClaimCooldownUpdatedEvent.InputTuple,
      MinClaimCooldownUpdatedEvent.OutputTuple,
      MinClaimCooldownUpdatedEvent.OutputObject
    >;

    "ReferralApplied(address,address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      ReferralAppliedEvent.InputTuple,
      ReferralAppliedEvent.OutputTuple,
      ReferralAppliedEvent.OutputObject
    >;
    ReferralApplied: TypedContractEvent<
      ReferralAppliedEvent.InputTuple,
      ReferralAppliedEvent.OutputTuple,
      ReferralAppliedEvent.OutputObject
    >;

    "ReferralBoostDurationUpdated(uint256,uint256)": TypedContractEvent<
      ReferralBoostDurationUpdatedEvent.InputTuple,
      ReferralBoostDurationUpdatedEvent.OutputTuple,
      ReferralBoostDurationUpdatedEvent.OutputObject
    >;
    ReferralBoostDurationUpdated: TypedContractEvent<
      ReferralBoostDurationUpdatedEvent.InputTuple,
      ReferralBoostDurationUpdatedEvent.OutputTuple,
      ReferralBoostDurationUpdatedEvent.OutputObject
    >;

    "ReferralCodeCreated(address,bytes32,uint256)": TypedContractEvent<
      ReferralCodeCreatedEvent.InputTuple,
      ReferralCodeCreatedEvent.OutputTuple,
      ReferralCodeCreatedEvent.OutputObject
    >;
    ReferralCodeCreated: TypedContractEvent<
      ReferralCodeCreatedEvent.InputTuple,
      ReferralCodeCreatedEvent.OutputTuple,
      ReferralCodeCreatedEvent.OutputObject
    >;

    "ReferralDiscountWithdrawn(address,uint256,uint32,uint256)": TypedContractEvent<
      ReferralDiscountWithdrawnEvent.InputTuple,
      ReferralDiscountWithdrawnEvent.OutputTuple,
      ReferralDiscountWithdrawnEvent.OutputObject
    >;
    ReferralDiscountWithdrawn: TypedContractEvent<
      ReferralDiscountWithdrawnEvent.InputTuple,
      ReferralDiscountWithdrawnEvent.OutputTuple,
      ReferralDiscountWithdrawnEvent.OutputObject
    >;

    "TokensClaimed(address,uint256,uint256)": TypedContractEvent<
      TokensClaimedEvent.InputTuple,
      TokensClaimedEvent.OutputTuple,
      TokensClaimedEvent.OutputObject
    >;
    TokensClaimed: TypedContractEvent<
      TokensClaimedEvent.InputTuple,
      TokensClaimedEvent.OutputTuple,
      TokensClaimedEvent.OutputObject
    >;

    "TreasuryWalletUpdated(address,address)": TypedContractEvent<
      TreasuryWalletUpdatedEvent.InputTuple,
      TreasuryWalletUpdatedEvent.OutputTuple,
      TreasuryWalletUpdatedEvent.OutputObject
    >;
    TreasuryWalletUpdated: TypedContractEvent<
      TreasuryWalletUpdatedEvent.InputTuple,
      TreasuryWalletUpdatedEvent.OutputTuple,
      TreasuryWalletUpdatedEvent.OutputObject
    >;
  };
}
