/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  TorqueDriftCars,
  TorqueDriftCarsInterface,
} from "../TorqueDriftCars";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "initialOwner",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "OwnableInvalidOwner",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "OwnableUnauthorizedAccount",
    type: "error",
  },
  {
    inputs: [],
    name: "ReentrancyGuardReentrantCall",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "carId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "rarity",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "version",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "hashPower",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "cooldownSeconds",
        type: "uint32",
      },
    ],
    name: "CarCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "carStates",
    outputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "address",
        name: "mint",
        type: "address",
      },
      {
        internalType: "uint8",
        name: "rarity",
        type: "uint8",
      },
      {
        internalType: "uint8",
        name: "version",
        type: "uint8",
      },
      {
        internalType: "uint256",
        name: "hashPower",
        type: "uint256",
      },
      {
        internalType: "uint32",
        name: "cooldownSeconds",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "carId",
        type: "uint256",
      },
      {
        internalType: "uint8",
        name: "rarity",
        type: "uint8",
      },
      {
        internalType: "uint8",
        name: "version",
        type: "uint8",
      },
    ],
    name: "createGameCar",
    outputs: [
      {
        internalType: "address",
        name: "carAddress",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "gameContract",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint8",
        name: "rarity",
        type: "uint8",
      },
      {
        internalType: "uint8",
        name: "version",
        type: "uint8",
      },
      {
        internalType: "uint256",
        name: "seed",
        type: "uint256",
      },
    ],
    name: "generateRandomHashPower",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "carAddress",
        type: "address",
      },
    ],
    name: "getCarState",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "owner",
            type: "address",
          },
          {
            internalType: "address",
            name: "mint",
            type: "address",
          },
          {
            internalType: "uint8",
            name: "rarity",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "version",
            type: "uint8",
          },
          {
            internalType: "uint256",
            name: "hashPower",
            type: "uint256",
          },
          {
            internalType: "uint32",
            name: "cooldownSeconds",
            type: "uint32",
          },
        ],
        internalType: "struct ITorqueDriftStructs.CarState",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint8",
        name: "rarity",
        type: "uint8",
      },
      {
        internalType: "uint8",
        name: "version",
        type: "uint8",
      },
    ],
    name: "getCooldownSeconds",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "getUserCarAddresses",
    outputs: [
      {
        internalType: "address[]",
        name: "",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "getUserCarCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "getUserCars",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "mint",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "hashPower",
            type: "uint256",
          },
          {
            internalType: "uint8",
            name: "rarity",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "version",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "slotIndex",
            type: "uint8",
          },
        ],
        internalType: "struct ITorqueDriftStructs.CarInfo[5]",
        name: "equippedCars",
        type: "tuple[5]",
      },
      {
        internalType: "uint8",
        name: "totalEquipped",
        type: "uint8",
      },
      {
        internalType: "uint256",
        name: "totalHashPower",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "getUserInventory",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "mint",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "hashPower",
            type: "uint256",
          },
          {
            internalType: "uint8",
            name: "rarity",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "version",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "slotIndex",
            type: "uint8",
          },
        ],
        internalType: "struct ITorqueDriftStructs.CarInfo[]",
        name: "ownedCars",
        type: "tuple[]",
      },
      {
        internalType: "uint8",
        name: "totalOwned",
        type: "uint8",
      },
      {
        internalType: "uint256",
        name: "totalInventoryHashPower",
        type: "uint256",
      },
      {
        internalType: "uint8[5]",
        name: "equippedSlots",
        type: "uint8[5]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_gameContract",
        type: "address",
      },
    ],
    name: "setGameContract",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "userCars",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "address",
        name: "carAddress",
        type: "address",
      },
    ],
    name: "userOwnsCar",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class TorqueDriftCars__factory {
  static readonly abi = _abi;
  static createInterface(): TorqueDriftCarsInterface {
    return new Interface(_abi) as TorqueDriftCarsInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): TorqueDriftCars {
    return new Contract(address, _abi, runner) as unknown as TorqueDriftCars;
  }
}
